### ISSUE TITLE
Mapbox takes over the whole view

### ISSUE THREAD

**Issue by programmin1** [mapbox/mapbox-common-ios#338]
I have Storyboard with UIStackview, with children: Mapbox, UITAbleView, other Stack view. 

When I run it the Mapbox takes the entire screen. It seems I cannot set a width, set a constraint like others can?
Furthermore when I "Capture View Hierarchy" I see none of the other views that are supposed to be within the same view as the Mapbox.
Why does it seem to take the full screen and not allow setting its height, constraints here?

<img width="570" alt="Screenshot 2024-10-22 at 11 34 03 PM" src="https://github.com/user-attachments/assets/815daafb-bdfc-4aee-a762-35a75aab4b13">

**Comment by persidskiy** [comment]
Hi, the `MapView` behaves like any other view, the issue should be fixed in your layout configuration.
